version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_ADDR=redis:6379
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
    - "${DB_PORT}:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    - ./mysql-config:/etc/mysql/conf.d
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  timer-phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql  
    depends_on:
      - db

volumes:
  mysql-data: